### ISSUE TITLE
Trackobot deck analysis

### ISSUE THREAD

**Issue by ganwell** [stevschmid/trackobot.com#11]
I created an algorithm to find the most common decks based on tracked games:

https://ganwell.github.io/card-complete.html

It would be interesting to try this with a large data-set.

**Comment by temas-hub** [comment]
How can get access to anonymized database of matches? I need to get real match history data. More than from my local matches(I played only 100 of matches and 10 of decks). But I'm planning to carry on analysis of thousands of matches with hundrends of decks to understand the best winning decks, most effective combos, etc. Can anyone help me?

**Comment by stevschmid** [comment]
Track-o-Bot data is only available to the individual user.
