### ISSUE TITLE
Uninstalling does not stop application

### ISSUE THREAD

**Issue by Boren** [stevschmid/trackobot.com#16]
When you uninstall the program it does not stop the running application and says "some files could not be removed". This results in the application entry getting removed, but the application still remains (and actually started on boot).

Happens on Windows 8.1
Solution: Stop application before uninstalling.

**Comment by stevschmid** [comment]
Thanks for your report. Please reopen the issue in https://github.com/stevschmid/track-o-bot if it still persists.
