### ISSUE TITLE
Possibility to Manually Add Matches to the History

### ISSUE THREAD

**Issue by der1agibert** [stevschmid/trackobot.com#17]
While I like the simplicity of your website and especially the option to define certain decks for the statistics, I feel like the option to manually add games might be worth considering. Just now, Track-o-Bot was not able to submit a match I got temporarily disconnected from. Resuming and finishing it, Hearthstone showed me the ususal dialogue along the lines "You got disconnected mid-game, and you now need to restart the client because it failed to fetch some data from the utility servers. Your recent outcome still counts". Track-o-Bot ran the entire time but seemed unable to get its required information to submit them. Of course, not having connection issues would be one way to address the problem, but seldom do we choose to lag or dc, I guess :)

Additionally, now that HS is out for mobile devices, keeping track of the games played on-the-go or just not on your computer is not possible as of now.

Being a compete layman and only having found threads about removing entries here, I do not know how much of a hassle it might pose to implement this feature but I thought I'd just chime in to bring up the issue.

**Comment by stevschmid** [comment]
Manually adding via the frontend is not on the plan right now. But adding games via the API is pretty straightforward. I'm waiting for someone to create a companion app which allows to add results easily :) Hit me up if you are interested.
