### ISSUE TITLE
RFC: Ability to track misplays

### ISSUE THREAD

**Issue by sgrif** [stevschmid/trackobot.com#19]
Hi there,

I'm happy to implement this feature myself but I wanted to get feedback on how well you think it fits into your roadmap for the application. There are often cases where I've made a misplay, and it's apparent either on that turn, or after the game is over. Any tracking of this would have to be entirely manual, but it'd be nice to input them, and then at the end of the day review the misplays that I've made so I can learn from them. It'd serve a similar function to a leak tracker in poker.

For this, we'd probably need to add a `"matches#show"` and `"matches#edit"` route. While this would add some slightly heavy feeling pages to the currently light UX, I think that future feature development will necessitate the addition of those regardless.

(As a side note, I'm the maintainer of Active Record and I'd love to submit a few PRs to clean up the models if you'd be open to that.)

**Comment by pencil** [comment]
Maybe a generic tagging system combined with some filtering mechanisms could be used to implement the functionality you suggest. It would allow users to separate and classify their matches in the ways that they find useful.

**Comment by stevschmid** [comment]
A generic tagging system would be lovely!

**Comment by stevschmid** [comment]
The upcoming version includes a tagging and filtering system as @pencil suggested. Hope that this helps tracking down your misplays @sgrif.

**Comment by gssjr** [comment]
@sgrif Who wouldn't love cleaner models?! :) I'd say go for it.
