### ISSUE TITLE
JSON API Should have a "last updated date" so we know when to load new data

### ISSUE THREAD

**Issue by clooth** [stevschmid/trackobot.com#20]

**Comment by emilesilvis** [comment]
@stevschmid is this worth making a PR for?

**Comment by stevschmid** [comment]
The first result already contains an `added` attribute which can be used for checking if there is new data.

**Comment by clooth** [comment]
A more ingenius approach would be to return the last modified date in a header only response so we mitigate almost all need of loading data :)
