### ISSUE TITLE
Make Decks available in the API

### ISSUE THREAD

**Issue by JulianEberius** [stevschmid/trackobot.com#26]
Hi,

I've started working on a tiny iOS [companion app for Track-o-Bot](https://github.com/JulianEberius/track-o-bot-ios/), since I play a lot of HS on iPad.

Basic functionality (authenticating & creating new results) works fine. As a next step, I wanted to be able to pick the Deck used in each game, and for that I need to be able to access the list of user-defined decks via the API. At the moment, this seems impossible. Using a URL like
    
    https://trackobot.com/profile/settings/decks.json?username=<username>&token=<token>

leads to an internal server error

    {"status":"500","error":"Internal Server Error"}

Would be real nice if you could at some point enable access to the decks via the API. 

Anyway, thanks for this nice, clean and minimal HS tracker!

**Comment by stevschmid** [comment]
That's a good idea! Will keep this in mind.

**Comment by bl4ck0r** [comment]
Would be awsome @stevschmid if you can implement this!

**Comment by bl4ck0r** [comment]
Any news on that ?

**Comment by stevschmid** [comment]
Not yet. Soonish hopefully.

**Comment by JulianEberius** [comment]
Solved with commit ce24f24c1dcf89ffe8efb4fa17e1184d7ee3500e
