### ISSUE TITLE
Undefined decks in deck stats

### ISSUE THREAD

**Issue by rshareef** [stevschmid/trackobot.com#28]
I incorrectly opened an issue in the main track-o-bot repo.

The link the the previous issue:
https://github.com/stevschmid/track-o-bot/issues/78

The gist of it is that I would like stats of how decks I have entered into trackobot match up against unknown decks/decks I have not entered into trackobot.

Thanks for working on a great tracker!

Best,
Rustom

**Comment by justinclayton** [comment]
+1 on this. Even if in the short term undetected opponent decks weren't excluded from deck stats, that would be a big plus.

Appreciate the work btw

**Comment by stevschmid** [comment]
Somewhat related to https://github.com/stevschmid/trackobot.com/issues/34

Will look into it with the new deck system.

**Comment by stevschmid** [comment]
Deployed with new update.
