### ISSUE TITLE
Remove Deck Association?

### ISSUE THREAD

**Issue by geraldhiller** [stevschmid/trackobot.com#29]
There are a few rare instances where an opponent's deck is wrongly recognized as a specific deck, and you don't want to create a new deck type, because a) it's either not a deck you want in your list or b) you just don't know which one the other guy played. In this case there does not seem to be a way to remove the deck association (so that the stats are not skewed) or did I overlook something?

Not a big issue, just a minor thing to help maximize stat accuracy.

**Comment by amarcadet** [comment]
:+1:

**Comment by stevschmid** [comment]
Yeah that option is missing. Hope to address this issue with the revamp of the deck system.

**Comment by stevschmid** [comment]
Deployed with new update.
