### ISSUE TITLE
Possibility to send decks when adding a game via API

### ISSUE THREAD

**Issue by LinogeFly** [stevschmid/trackobot.com#30]
Hi,

It would be great to have an ability to send player's and opponent's decks when adding new games via API. To my understanding decks have IDs. So another useful feature would be a service that returns profile decks with their IDs when you send username and token.

One of the main features that I like in Track-o-bot is the ability to have deck statistics. Quite often I play on a phone and I created a simple site where I can upload games to trackobot.com so I have better statistics. Unfortunately, I'm missing the feature of having deck statistics for mobile games because I can set only class when adding a game via API. No major plans yet on making that site public. It's more like a playground at the moment where I learn some web related technologies.

Best regards,
Alexey.

**Comment by stevschmid** [comment]
Hey Alexey. I'll look into it.

**Comment by LinogeFly** [comment]
Great! Looking forward to it :)

**Comment by stevschmid** [comment]
Deployed with new update. `opponent_deck_id` and `deck_id` now `POST`able.

**Comment by LinogeFly** [comment]
Awesome, thanks a lot!
