### ISSUE TITLE
Filter decks by class

### ISSUE THREAD

**Issue by alexeibs** [stevschmid/trackobot.com#33]
It would be nice to show only, for example, paladin decks when user is changing a deck type for paladin in match history. Now the list of options contains all decks configured before.

**Comment by stevschmid** [comment]
You can simply search for "Paladin" to list all the paladin matches in the history.

**Comment by alexeibs** [comment]
Sorry. I chose a wrong title for this issue and described the problem poorly :(  It's not about search in match history. It's about this form:
![image](https://cloud.githubusercontent.com/assets/1247013/12763610/5fc6c82c-ca06-11e5-954a-47bb88abcf6d.png)

**Comment by stevschmid** [comment]
Ah I see what you mean. Will try to address this in the upcoming deck system update.

**Comment by stevschmid** [comment]
Deployed with new update.
