### ISSUE TITLE
Deck vs. Class

### ISSUE THREAD

**Issue by geraldhiller** [stevschmid/trackobot.com#34]
Would anyone else care for a stat view that lists the win percentages of one deck against the other classes (rather than against other decks)?

I think it would be neat and in some cases more accurate, as decks are not always identified correctly and different deck types often melt into each other. It's not really interesting to know how well you perform with a particular class. You're always worried about the performance of individual decks. So the more information you get about how a different deck performs in specific scenarios, the better.

**Comment by satyrius** [comment]
(+1) I like stats for decks more, because I play a lot of decks per class and want to see distinct winrate for each. But I have so many decks configured and found that "against deck" section is flooded. It will be handy to check winrate for the deck against a class.

**Comment by satyrius** [comment]
@stevschmid, can I make a pull request, or we should wait for your confirmation?

**Comment by stevschmid** [comment]
I'm currently planing on revamping the whole deck system. Maybe I can address this issue as well.

**Comment by stevschmid** [comment]
Somewhat addressed with the new update ("Other <Classname>").
