### ISSUE TITLE
Time summary

### ISSUE THREAD

**Issue by satyrius** [stevschmid/trackobot.com#35]
It would be nice to see time total played for deck/class on the stats page.

**Comment by stevschmid** [comment]
You can calculate this easily via API (json/csv) yourself.

**Comment by satyrius** [comment]
Yes I can, but it looks like stat that could be easily calculated and shown on the page.

**Comment by stevschmid** [comment]
That is true, but I'm not sure that the metric is useful for everybody. It could frustrate some people "Ugh, did I really play 12 hours in the last 3 days?". I personally don't like the time tracking in Steam.

But I'm open to this if there is a demand and good reasons.
