### ISSUE TITLE
Remember stats page filter

### ISSUE THREAD

**Issue by satyrius** [stevschmid/trackobot.com#36]
When I go to the stats page I always do the same thing – set filter to *Ranked* for *Current month*. It would be nice to save this as preferred filter for user (store in cookies, session, wherever).

<img width="710" alt="screenshot 2015-12-19 18 25 21" src="https://cloud.githubusercontent.com/assets/278630/11913701/37f8eb5a-a67e-11e5-97ee-e049a1d58888.png">

**Comment by stevschmid** [comment]
Makes sense. I'll look into it.

**Comment by stevschmid** [comment]
Deployed with new update.
