### ISSUE TITLE
Improvements to Decks feature

### ISSUE THREAD

**Issue by JustinasDaugela** [stevschmid/trackobot.com#37]
I'd like to develop a feature I'd find very useful myself:

- Allow a more convenient way of importing/exporting decks. 

This could be a simple JSON file dump option from your current deck list, with the ability to also import the file. Would allow users to conveniently share deck lists, in time providing the ability for everyone to see statistics not only versus classes, but versus specific decks instead.

**Comment by JustinasDaugela** [comment]
@stevschmid I'd like to get working on the feature if that's ok

**Comment by stevschmid** [comment]
What about the ability to import/export a deck via a string? (string contains name, class and card ids)

That would allow to add decks very easily by simply entering a string.

**Comment by JustinasDaugela** [comment]
@stevschmid sure, that sounds good as well. I'll develop this and make a PR. Thanks
