### ISSUE TITLE
Options for editing a match do not show class but only deck name

### ISSUE THREAD

**Issue by gpiancastelli** [stevschmid/trackobot.com#41]
When editing a match, the control by which you can select a different deck than the one recognized by the system only shows the deck names instead of showing both the deck name and the class name. Naming a deck with the class name also (e.g. "Freeze Mage" instead of "Freeze") can be redundant in the UI because deck names are always shown alongside their class name... except in the mentioned widget.

**Comment by stevschmid** [comment]
Most people call the deck "Freeze Mage", and a "[Mage] Freeze Mage" would make it unnecessary long. That being said, I'm looking into revamping the deck system soon.
