### ISSUE TITLE
Deck stats show lines for decks that have never been played/encountered

### ISSUE THREAD

**Issue by gpiancastelli** [stevschmid/trackobot.com#42]
The table in the deck stats page shows lines for every defined deck, even decks that have never been played/encountered. In the case many decks have been defined, the page results unnecessarily long. Please show only stats for relevant decks, i.e. decks played and decks with actual matches against played decks.

**Comment by stevschmid** [comment]
Thanks for the suggestion. I'll look into it.

**Comment by stevschmid** [comment]
Deployed with new update.
