### ISSUE TITLE
Support cross domain access for API

### ISSUE THREAD

**Issue by salaj1986** [stevschmid/trackobot.com#43]
Hello,

I'd like to access data via the provided API (https://trackobot.com/profile/history.json?username=USER&token=YOUR_API_TOKEN). The problem is that if I do this via JS from within another domain it fails due to a cross domain request.
Will it be supported? (Or maybe I'm missing something?)

Thanks!

**Comment by stevschmid** [comment]
It will not be supported from my side. I guess you can write a small proxy API.
