### ISSUE TITLE
API auth

### ISSUE THREAD

**Issue by Mathbl** [stevschmid/trackobot.com#5]
Hello! 

First of all, good job on track-o-bot! That's also great to open source it.

I began working on a little companion Android App that will use the API.

At first, I'll show a "login" screen so the user enters his username and token. I'd like to have a way to ask the API if these credentials are valid.

As for now, I could try to get the history or any other json, and if it does return an error I would take for granted that the credentials are not correct.

But I think that would be a nice addition to have a simple "auth".

Thanks!

**Comment by emilesilvis** [comment]
@Mathbl @stevschmid if you're still interested in this, I can have a look?

**Comment by Mathbl** [comment]
I don't know if it would be useful for others. As for myself, I do not need it anymore. I'll close this. Thanks!

**Comment by emilesilvis** [comment]
Thanks @Mathbl :smile:
