### ISSUE TITLE
Request: create an open database of hearthstone matches

### ISSUE THREAD

**Issue by benraziel** [stevschmid/trackobot.com#6]
Thank you for developing track-o-bot, great stuff!

Currently, there's no open database of hearthstone match history data (that i know of). Such an open database would be immensely useful for people wanting to do statistical analysis and machine learning work around hearthstone. 

I suggest adding an opt-in way for a user to make his match history publicly available. Adding a "make my match history public" checkbox in the settings page will do the trick.

We could then display the match history of all users who opted-in, in a similar way to how your personal match history is displayed in your profile.

If this seems like a reasonable idea to you (from a privacy/product standpoint), I'm willing to implement this feature.

**Comment by stevschmid** [comment]
I will close this for now.

**Comment by salaj1986** [comment]
Any news on this?

**Comment by stevschmid** [comment]
Unfortunately, no.
