### ISSUE TITLE
Add new (Karazhan) archetypes

### ISSUE THREAD

**Issue by soli** [stevschmid/trackobot.com#65]
Hi,

as posted [on reddit](https://www.reddit.com/r/trackobot/comments/51s169/request_for_new_archetypes/) I think it would be necessary (or at least nice) to have updated archetypes now that KARA is out.

I can write a pull request if you like (am I right that only trackobot.com/db/decks.json needs to be updated?).

As pointed out in the reddit post, a probably even better idea would be to have an automatically updated list of archetypes. However, a reliable source has to be decided upon. TempoStorm's [Meta Snapshot](https://tempostorm.com/hearthstone/meta-snapshot/) seems reasonable, ViciousSyndicate's [Data Reaper Report](http://www.vicioussyndicate.com/vs-data-reaper-report-17/) that relies on trackobot might also be quite good.

Tell me what you think, and if I can help (I'm not a rubyist, but that wouldn't be the first time I have to write a pull-request in a language I don't use :P).

**Comment by stevschmid** [comment]
I like a curated approach. And I'm just waiting for the dust to settle to update the decks again. Please post your ideas for new deck types to the subreddit.
