### ISSUE TITLE
Inconsistent/changing casing in API results

### ISSUE THREAD

**Issue by JulianEberius** [stevschmid/trackobot.com#82]
At some point in time, the /stats part of the API changed to use lower-cased hero names, e.g., "priest" instead of "Priest". The upper-cased variants were used in the past, and are still used in all other parts of the API, e.g. /profile. This is problematic for API clients that rely on these keys to extract data. Two questions:

1.) Will the other parts of the API also change to use lower-case hero names, so that the usage is consistent again?
2.) Is there a way to be aware of API changes before they are deployed, e.g., some feed to follow? This would help in migrating third-party clients to new API versions.

Thanks,
Julian

**Comment by theanine** [comment]
You could just always normalize these on the client-side, right?

**Comment by JulianEberius** [comment]
You're absolutely right that a more robust client should be able to deal with that, and future version of my [iOS client](https://github.com/JulianEberius/track-o-bot-ios) will ;-) It originally viewed the hero names as a set of constant identifiers, not (mutable) data, so it had some code in the style of `HEROES.flatMap { h in data[h] as? ... }`. Originally, the API used the same hero identifiers throughout, so this was fine. I can adapt of course.

Still, I think consistent use of identifiers (same on every endpoint) and documenting changes are good for a public API used by third-parties, so I wanted to at least start some discussion. I hope I don't come around as an ungrateful or entitled, I know TrackOBot is done for free.

**Comment by JulianEberius** [comment]
Closing, not relevant anymore.
